# Generated by Django 4.0 on 2023-03-20 11:14

import app.bison_utils.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_id_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, default=app.bison_utils.util.generate_otp, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
