# Generated by Django 4.0 on 2023-03-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_managers_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
